### ISSUE TITLE
Extension cannot load the cartridges on Windows

### ISSUE THREAD

**Issue by eismail-aiopsgroup** [redvanworkshop/sfcc-cartridge-overrides-vscode-extension#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Bug

Hello there,

I wasn't able to make the extension work on my machine running Windows. The issue is that the extension expects all file paths to be with forward slashes while on Windows they are returned with backslashes.

For example here:
`return vscode.workspace.findFiles(includePattern, excludePattern).then((files) => processFiles(files))`

I was able to fix the regular expressions in a few places and it started working but partially. Looks like there are many places where the slashes are checked and the checks are always expecting forward slashes - regular expressions, lastIndexOf(), split(), join() etc.

### Steps To Reproduce

1. Try to load the cartridges on Windows where vscode.workspace.findFiles returns the file paths with backslashes. 
2. The extension throws the following errors in Log (Window) output panel (because **match()** returns null while the extension directly checks for the length property):
```
[2022-06-16 18:15:43.238] [renderer1] [error] Cannot read properties of null (reading 'length'): TypeError: Cannot read properties of null (reading 'length')
    at c:\Users\MyUserName\.vscode\extensions\redvanworkshop.sfcc-cartridge-overrides-1.0.0\extension\Cartridges.js:315:23
    at Array.forEach (<anonymous>)
    at processFiles (c:\Users\MyUserName\.vscode\extensions\redvanworkshop.sfcc-cartridge-overrides-1.0.0\extension\Cartridges.js:309:18)
    at c:\Users\MyUserName\.vscode\extensions\redvanworkshop.sfcc-cartridge-overrides-1.0.0\extension\Cartridges.js:513:89
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-16 18:18:20.337] [renderer1] [error] Cannot read properties of null (reading 'hash'): TypeError: Cannot read properties of null (reading 'hash')
    at BlameViewProvider.<anonymous> (c:\Users\MyUserName\.vscode\extensions\huizhou.githd-2.2.4\out\src\blameViewProvider.js:178:29)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\MyUserName\.vscode\extensions\huizhou.githd-2.2.4\out\src\blameViewProvider.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
3. The list of cartridges cannot be loaded.

### Expected Behavior

The extension supports both forward- and backslashes.

### Screenshots
![image](https://user-images.githubusercontent.com/80893079/174107017-b73b76f0-99a4-4f83-afd3-ca26ff55a91e.png)

### Environment

```markdown
- OS: Windows 10
- Node: 16.9.1
- npm: 7.21.1
```

**Comment by manifestinteractive** [comment]
This should be resolved now in https://marketplace.visualstudio.com/items?itemName=PeterSchmalfeldt.sfcc-cartridge-overrides

**Comment by eismail-aiopsgroup** [comment]
Hello @manifestinteractive , 
Tried to install v1.0.1 but the issue still exists.
```
[2022-07-21 10:44:02.164] [renderer1] [error] Cannot read properties of null (reading 'length'): TypeError: Cannot read properties of null (reading 'length')
    at c:\Users\Enis Work\.vscode\extensions\peterschmalfeldt.sfcc-cartridge-overrides-1.0.1\extension\Cartridges.js:315:23
    at Array.forEach (<anonymous>)
    at processFiles (c:\Users\Enis Work\.vscode\extensions\peterschmalfeldt.sfcc-cartridge-overrides-1.0.1\extension\Cartridges.js:309:18)
    at c:\Users\Enis Work\.vscode\extensions\peterschmalfeldt.sfcc-cartridge-overrides-1.0.1\extension\Cartridges.js:513:89
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by manifestinteractive** [comment]
@eismail-aiopsgroup sorry, misunderstood this one, thought it was related to the workspace path issue, but it's the path separator issue not being pulled from the OS ( node has a variable just for that ).  I will get a fix out for that next.  Sorry I missed that one.

**Comment by eismail-aiopsgroup** [comment]
@manifestinteractive no worries at all! Please let me know if I can help somehow.

**Comment by manifestinteractive** [comment]
That hard coded path is all over, man, totally dropped the ball on that one.  Fortunately node has a built in `path.sep` I can use for all those custom RegExp patterns.  I will get this working again on macos after replacing all these, commit the code, and pull it down on a windows laptop to retest.  Might be a day or so, as this pattern is all over the place `/^(.+)\/cartridges\/([^/]+)\/cartridge\/(.+)$/` and that's just gross.  Using the following seems to work:

```
new RegExp(`^(.+)${path.sep}cartridges${path.sep}([^${path.sep}]+)${path.sep}cartridge${path.sep}(.+)$`)
```

**Comment by eismail-aiopsgroup** [comment]
Yes, I was also able to partially make it work like this but the issue is other places are also relying on the hard-coded separator - other (smaller) regular expressions, lastIndexOf(), split(), join() etc. And on some places, we can't just replace the separator but also need to fix the escaping issues.

I even tried to play with the Windows and VSCode settings hoping there's something wrong on my machine because I was wondering how come this wasn't reported until now. I shouldn't be the only one using Windows. :)

**Comment by manifestinteractive** [comment]
@eismail-aiopsgroup This should be working on https://marketplace.visualstudio.com/items?itemName=PeterSchmalfeldt.sfcc-cartridge-overrides ... you mind retesting this?  I was able to get it to work on Windows 10 & 11 after these fixes.

**Comment by eismail-aiopsgroup** [comment]
@manifestinteractive Works pretty fine now, thanks! 

Now I have another issue that some of our integration cartridges are located in a different directory structure but I will investigate further if a code change would be needed or can be fixed just with configuration. 

The issue can be closed.
